'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Res1
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Pifagor_Matrix.Res1", GetType(Res1).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ВЫЧИСЛЕНИЕ СРОКА СТАБИЛЬНОСТИ БРАКА
        ''' 
        ''' Данная авторская разработка предлагается вам не столько для работы с людьми, сколько как тема для размышления и проверки теории на практике. 
        ''' В основу этого метода заложена фигура, которая состоит из квадратов, но имеет новое качество - объем. Речь идет о Кубе. Из курса школьной геометрии вы знаете, что объем вычисляется умножением трех его измерений. Способ вычисления объема достаточно прост, но остается самое главное - выяснить, что такое те самые измерения, кото [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property About() As String
            Get
                Return ResourceManager.GetString("About", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Следует помнить, что даже с одинаковой датой рождения, люди всё равно разные. В жизни, в силу каких-либо обстоятельств одни цифры переходят в другие, например, 11 могут превратится в 8 или наоборот, а 66 могут превратится в 7. при чём такие переходы могут быть постоянными, а могут быть и временными, в зависимости от ситуации, например, в гневе, 66 могут превращаться в 666, за счет каких-то других цифр и тд и тп.
        '''</summary>
        Friend Shared ReadOnly Property Abt() As String
            Get
                Return ResourceManager.GetString("Abt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ЗНАЧЕНИЕ ПЕРВОЙ СТРОКИ ПСИХОМАТРИЦЫ - ЦЕЛЕУСТРЕМЛЕННОСТЬ
        ''' 
        ''' Первая строка (1, 4, 7) отвечает за целеустремленность человека, умение отстоять свои взгляды, ставить перед собой цели и задачи. Проведем анализ первой строки. 
        ''' Цифр нет - человек не ставит перед собой цели и задачи, надеясь на случай или других людей, его достаточно легко переубедить и заставить отказаться от своих планов. 
        ''' Одна цифра - слабая целеустремленность; человек может включиться в спор, но это не означает, что он желает достичь рез [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property CE() As String
            Get
                Return ResourceManager.GetString("CE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ЗНАЧЕНИЕ СПАДАЮЩЕЙ ДИАГОНАЛИ – ДУХОВНАЯ ДИАГОНАЛЬ
        ''' 
        ''' Диагональ, содержащая цифры 1, 5, 9 (спадающая), отвечает за духовность человека, его устремление к духовной близости и высшему началу - Бог, высший разум и т. д. Рост духовности человека возрастает в зависимости от количества цифр в данной линии. Можно сказать, что до пяти цифр духовность человека постепенно усиливается от бездуховности при отсутствии цифр до максимума при пяти цифрах. Если эта линия содержит более пяти цифр (6 и более), то мы будем го [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property DU() As String
            Get
                Return ResourceManager.GetString("DU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ЗНАЧЕНИЕ ЦИФРЫ «1» 
        '''@@@@@
        '''ХАРАКТЕР «1»
        ''' 
        ''' Цифра 1 в психоматрице отвечает за характер человека, его волевые качества, силу стремления к власти, способность отстоять свои взгляды. 
        ''' Характер «ОДНА 1»: безвольный, эгоистичный. Можно сказать, что это один из самых сложных характеров. Им обладают люди, противоречивые по своей природе. Дело в том, что, имея безвольный характер, они избегают принятия любых решений, стараясь переложить их на плечи другого, человека. Убегая от принятия решения, они отчаянно им [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property f1() As String
            Get
                Return ResourceManager.GetString("f1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ЗНАЧЕНИЕ ЦИФРЫ «2»
        '''Цифра 2 в числовой системе Пифагора обозначает энергию человека. Нужно понять, что энергия в данном случае - это действия человека в семье, на работе, в обществе. Энергия, обозначаемая цифрой 2, не совсем идентична известной энергии органов человека, которую в акупунктуре называют Чи (или Ци) меридианов. В дальнейшем вы увидите, что они все же имеют соприкосновение через взаимный переход цифр 2 и 4. Мы говорим, что человек энергичный, если он может поставить перед собой цель, найти пути  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property f2() As String
            Get
                Return ResourceManager.GetString("f2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ЦИФРА «3» И ЕЕ КОЛИЧЕСТВЕННЫЕ ХАРАКТЕРИСТИКИ
        ''' Когда вы приступите к оценке этой цифры в психоматрице, не забудьте, что она входит в несколько линий, а именно - в столбец (1, 2, 3), восходящую диагональ (3, 5, 7) и 3-ю строку (3, 6, 9). Это очень важно знать и помнить при определении влияния цифры 3. 
        '''
        ''' Дело в том, что не все люди могут явно раскрыть себя в науках. Это связано с тем, что для этого необходим определенный набор цифр: 22, 55, 9 (или более), 33 (и более), если речь идет о точных науках. Но ес [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property f3() As String
            Get
                Return ResourceManager.GetString("f3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ЦИФРА «4» И ЕЕ КОЛИЧЕСТВЕННЫЕ ХАРАКТЕРИСТИКИ
        '''Можно ли, используя только дату рождения, сказать о состоянии здоровья больше чем: &quot;слабое&quot;, &quot;нормальное&quot;, &quot;сильное&quot;? В Древнем Китае существовала нумерологическая система, которая была совмещена со схемой взаимодействия органов концепции У-Син (пять первоэлементов). В нашей книге вы найдете эту схему, но расширенную на 10 органов, так как в китайской нумерологической схеме разбирались соответствия между органами Чжан (5 органов) и цифрами от 5 до 9. Только испо [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property f4() As String
            Get
                Return ResourceManager.GetString("f4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ЦИФРА «5» И ЕЕ КОЛИЧЕСТВЕННЫЕ ХАРАКТЕРИСТИКИ
        '''Цифра 5 в психоматрице отвечает за логику и интуицию человека, что, в свою очередь, определяет возможности человека строить планы и анализировать ситуацию, разбираться в точных науках и технике. Это непосредственные характеристики цифры 5, но существуют и косвенные характеристики, которые связаны с тем, что цифра 5 занимает центральное положение в психоматрице, а следовательно, принадлежит четырем линиям, которые могут захватить цифру и включить ее в свои характ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property f5() As String
            Get
                Return ResourceManager.GetString("f5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ЦИФРА «6» И ЕЕ КОЛИЧЕСТВЕННЫЕ ХАРАКТЕРИСТИКИ
        '''Цифра 6 - одна из самых противоречивых и сложных в данной нумерологической системе. Прежде чем мы запишем характеристики этой цифры, предлагаю некоторые комментарии к их объяснению. Самое первое, что мы можем вспомнить, - это Откровение святого Иоанна Богослова: &quot;Здесь мудрость. Кто имеет ум, тот сочти число зверя, ибо это число человеческое; число его шестьсот шестьдесят шесть&quot;. Итак, число &quot;666&quot; - число зверя, или число сатаны. Кажется, мы попали в мир легенд  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property f6() As String
            Get
                Return ResourceManager.GetString("f6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ЦИФРА «7» И ЕЕ КОЛИЧЕСТВЕННЫЕ ХАРАКТЕРИСТИКИ
        '''Цифру 7 всегда связывали с понятием везения (удачи). Иногда эту цифру называют знаком ангела. 
        '''
        ''' Вероятнее всего, более или менее логичное объяснение такой интерпретации цифры 7 можно дать из примера с землепашцем, который, обрабатывая землю с помощью плута, всегда надеялся на счастливый, удачный исход своего дела. Проще говоря, пахарь рассчитывал на везение, которое ему могло послать только небо - Бог, ангел, Святой Дух или святые мощи. Человеку некуда было о [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property f7() As String
            Get
                Return ResourceManager.GetString("f7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ЦИФРА «8» И ЕЕ КОЛИЧЕСТВЕННЫЕ ХАРАКТЕРИСТИКИ
        '''Цифра 8 - одна из самых важных цифр, определяющая всю психоматрицу человека, так как именно ее устойчивость или появление в психоматрице обусловит многие качества, необходимые человеку. Эта цифра отвечает за чувство долга к близким (родители, семья), чувство терпимости и доброты - качества, которые мы должны проявлять по отношения к родителям и близким людям. 
        '''
        ''' Почему именно 8 отвечает за это качество? Объяснение очень простое. Напишем список самых близких ро [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property f8() As String
            Get
                Return ResourceManager.GetString("f8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ЦИФРА «9» И ЕЕ КОЛИЧЕСТВЕННЫЕ ХАРАКТЕРИСТИКИ
        '''Цифра 9 в психоматрице отвечает за ум, память и ясновидение человека. Почему именно эта цифра? Она следует за цифрой 8, и ее характеристика должна быть связана со значением этой цифры. Восемь отвечает за долг по отношению к близким людям, особенно родителям. Естественно, что люди переживают смерть родителей, и именно на этот случай предназначена цифра 9. После смерти родителей долг переходит в новое качество - необходимо помнить о них, и поэтому цифра 9 отвечает [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property f9() As String
            Get
                Return ResourceManager.GetString("f9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1 - Характер человека, эго, воля, осознание
        '''   нет - 
        '''   1 - Если в расчете всего одна единица, то этот человек — утонченный эгоист. Не обращая ни на что вокруг внимания, он стремится из любого положения извлечь максимальную выгоду прежде всего для себя. Его мало интересуют другие люди и то — чем и как они живут. Главное, что живет и должен жить только он один.
        '''   11 - У человека присутствует слабо выраженный эгоизм (все время себя хвалит, как на продажу, боится переоценить)
        '''   111 - Человек обладает хо [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property g1() As String
            Get
                Return ResourceManager.GetString("g1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2 - Биоэнергетика, страстность, сексуальность
        '''   нет - 
        '''   2 - Обычные в биоэнергетическом отношении люди. Все же биоэнергии маловато. Эти люди должны избегать стрессовых ситуаций, слишком сильных эмоций, обязательны занятия физкультурой или спортом, эффективнее же всего — йога. Такие люди очень чувствительны к изменениям в атмосфере.
        '''   22 - Присутствует достаточное количество биоэнергии, способен делится энергией с другими, может стать целителем. В семье таких людей в принципе редко у кого бывают нервн [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property g2() As String
            Get
                Return ResourceManager.GetString("g2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3 - Внутренний склад человека, хозяйственность, порядочность
        '''   нет - обычно очень чистоплотные или пунктуальные люди; что-то выделяет их из окружающей среды - они постоянно что-то чистят, трут; женщины без троек - отличные хозяйки, но несколько раздражают своим стремлением к чистоте; мужчины тщательно следят за своим внешним видом и не терпят, когда их подруги опаздывают на свидания. Детей воспитывают в строгости. Любят наблюдать себя в зеркале, произносить умные, витиеватые фразы.  ропотливый труд выполн [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property g3() As String
            Get
                Return ResourceManager.GetString("g3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 4 - Здоровье, сексуальность
        '''   нет - Здоровье очень слабое, человек с детства подвержен различным заболеваниям; болеть будет тем больше, чем больше у него двоек, потому что так или иначе будет вынужден отдавать свою энергию.
        '''   4 - Здоровье среднее, необходимо закалять организм; болезни подступают к старости.
        '''   44 - От природы это очень крепкий человек с повышенным темпераментом.
        '''   444 - Люди с очень крепким здоровьем и огромными сексуальными возможностями. Мужчины от природы очень сильные физически.        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property g4() As String
            Get
                Return ResourceManager.GetString("g4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 5 - Интуиция
        '''   нет - Открытый канал при рождении, поэтому этот человек всегда пытается что-то предпринять, что-то доказать, всегда голова в раздумье, сам в эксперименте, в расчете. Жизненный опыт показывает, что с этим человеком трудно жить. Все достается (пробивает) своей головой.
        '''   5 - Канал связи открыт. Эти люди совершают гораздо меньшее число ошибок и в жизни и вообще, могут правильно рассчитать ситуацию и извлечь из нее максимальную пользу.
        '''   55 - Сильно развитая интуиция. Могут предугадывать хо [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property g5() As String
            Get
                Return ResourceManager.GetString("g5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 6 -  Степень заземленности, логика, расчетливость
        '''   нет - Такой человек пришел на землю приобрести ремесло, физический труд необходим, но он его не любит.
        '''   6 - Человек в какой-то мере заземлен, можно заниматься творчеством или точными науками, но физический труд является обязательным условием существования.
        '''   66 - Человек очень заземлен. Эти люди тянутся к физическому труду, хотя, как раз для них он не обязателен.
        '''   666 - Знак сатаны. Люди повышенного темперамента, обаятельные, неизменно становящие [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property g6() As String
            Get
                Return ResourceManager.GetString("g6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 7 - Мера таланта, связь с высшими силами
        '''   нет - Этот человек родился, чтобы зарабатывать семерки, а заработать их можно только стараниями. Очень тяжелая жизнь. Почти всегда приведет к религии.
        '''   7 - Божья искра. Таким людям живется значительно легче, есть талант, но неярко выражен
        '''   77 - Это очень сильный знак ангелоподобия, если его развивать полностью. Человек очень одаренный, музыкальный, имеет художественный вкус, сможет рисовать. Если в расчете две единицы, то его эгоизм может руководить им и ег [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property g7() As String
            Get
                Return ResourceManager.GetString("g7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 8 - Чувство долга
        '''   нет - Соответствует почти полному отсутствию чувства долга. Человек никогда не считает себя кому-то обязанным, не спешит отдавать взятое и пропускает все назначенные сроки.
        '''   8 - Можно сказать, что эти люди наделены тем, что называется чувством долга: они ответственны, добросовестны, точны в делах.
        '''   88 - Очень развито чувство долга. Этих людей всегда отличает желание помочь другим, особенно слабым, больным, одиноким. Считают себя ответственными за кого-либо или что-либо. Обычно пр [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property g8() As String
            Get
                Return ResourceManager.GetString("g8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 9 - Интеллект
        '''   нет - Человек от рождения не блестит умом, ему необходимо умственно развиваться, много и усердно учиться, но это ему дается не просто.
        '''   9 - Человек должен упорно трудиться, чтобы заработать хотя бы еще одну девятку.
        '''   99 - У человека с рождения умная голова. Они должны учиться, т.к. многого могут добиться.
        '''   999 - Очень умны от природы, слабо учится, т.к. все дается. В учении вообще не прилагают никаких усилий: все, что требует от них каких-либо умственных затрат, не представляет дл [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property g9() As String
            Get
                Return ResourceManager.GetString("g9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to В вашей дате присутствует год рождения больше 1999. Согласно автору книги, если год рождения 2000 и выше, то для правильного расчета нужна корректировка даты. Автор на этом не настаивает, так что возможно расчёт будет правильным и после 2000 года. Но, если для вас это важно или интересно, можете ознакомится с правилами корректировки в книге Александра Александрова – &apos;Дата рождения - ключ к пониманию человека&apos;..
        '''</summary>
        Friend Shared ReadOnly Property god2000() As String
            Get
                Return ResourceManager.GetString("god2000", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ЗНАЧЕНИЕ ВТОРОГО СТОЛБЦА – МАТЕРИАЛЬНОЕ БЛАГОПОЛУЧИЕ
        ''' 
        ''' Второй столбец (4, 5, 6) включает очень сложные и активные цифры: 4 - здоровье человека, 5 - логика и интуиция, 6 - склонность к физическому труду и мастерству. Все три цифры требуют больших затрат силы воли человека для их раскрытия (попробуйте заставить себя соблюдать диету для укрепления здоровья, составить долгосрочный и реальный план действий, выполнить физическую работу). Если цифры, составляющие данную линию, требуют волевого участия, то и вся [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property MA() As String
            Get
                Return ResourceManager.GetString("MA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ЗНАЧЕНИЕ ВОСХОДЯЩЕЙ ДИАГОНАЛИ – ПЛОТСКАЯ ДИАГОНАЛЬ
        ''' 
        ''' Восходящая диагональ (3, 5, 7) определяет плотские интересы человека: темперамент в интимной жизни, стремление красиво 
        ''' значение этой линии - интимная жизнь человека, его темперамент и потребность в близости. Этот вопрос - один из самых важных в семье. Чаще всего приводит к распаду семьи несовместимость в темпераменте, Позволю себе шутку, которая достаточно хорошо отражает различие в силе темпераментов (только не забывайте, что это всего лишь шутка). [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property PL() As String
            Get
                Return ResourceManager.GetString("PL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ЗНАЧЕНИЕ ТРЕТЬЕЙ СТРОКИ ПСИХОМАТРИЦЫ - ПРИВЫЧКИ
        ''' 
        ''' Третья строка (3, 6, 9) указывает на стабильность человека (привычки, привязанности, боязнь и нежелание перемен). 
        ''' Цифр нет или одна цифра - человек - революционер по духу. Он стремится все изменить вокруг себя, меняет окружение, место работы, оспаривает практически все, стремясь изменить всех и вся. 
        ''' Две цифры - человек легок на подъем, но уже может остановить свой революционный порыв (при желании). 
        ''' Три цифры - нестабильный в привычках человек. Мо [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property PR() As String
            Get
                Return ResourceManager.GetString("PR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Первое число показывает, какие качества необходимо усилить и развить человеку, чтобы достичь поставленной перед ним цели. 
        ''' У многих читателей возникает вопрос: «Кто ставит цель перед человеком?». Вспомните зоологию. Любой зоолог вам смело скажет, что каждое животное выполняет определенную роль в биосфере Земли, занимает свою биологическую нишу. Например, хищники - это «санитары», которые убивают слабых и больных животных, осуществляя тем самым естественный отбор. Так как природа отвела строгую роль каждом [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property PRC() As String
            Get
                Return ResourceManager.GetString("PRC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ЗНАЧЕНИЕ ПЕРВОГО СТОЛБЦА -  САМООЦЕНКА
        '''
        '''  Общее количество цифр первого столбца (1, 2, 3) определяет силу самооценки человека. В этом качестве заключено желание выделить себя из толпы, показаться более яркой личностью (ум, разговор, одежда, косметика и т. д.). Очень часто в литературе по нумерологии первому столбцу приписывается качество эгоизма. Думаю, что это необоснованно, так как самооценка человека не имеет с эгоизмом ничего общего, тем более что за эгоизм человека будет отвечать другая характеристик [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SA() As String
            Get
                Return ResourceManager.GetString("SA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ЗНАЧЕНИЕ ВТОРОЙ СТРОКИ ПСИХОМАТРИЦЫ - СЕМЕЙНОСТЬ
        ''' 
        ''' Вторая строка (2, 5, 8) отвечает за качество семьянина, стремление иметь семью, находиться среди своих близких. Проведем анализ характеристики: 
        ''' Цифр нет - человек не семьянин. Это означает, что семья у него стоит на последнем месте. Такие люди, как правило, не спешат создавать семью (их больше интересует работа, карьера, друзья и др.). 
        ''' Одна и две цифры - человек помнит, что семью надо создать, но особых усилий в этом направлении не проявляет. Ждет  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SE() As String
            Get
                Return ResourceManager.GetString("SE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ЗНАЧЕНИЕ ТРЕТЬЕГО СТОЛБЦА - ТАЛАНТ
        ''' 
        ''' Третий столбец (7, 8, 9) психоматрицы отвечает за талант человека. Чем больше цифр - тем сильнее талант. Это не означает, что если эта линия очень сильная (5 цифр, чтобы не было перегрузки), то человек станет непременно талантливым. Помните, на раскрытие таланта влияют многие цифры и линии психоматрицы: характер, самооценка, целеустремленность, энергетика, здоровье, везение и другие. Именно комбинация многих характеристик и волевое усилие самого человека дают достижен [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property TA() As String
            Get
                Return ResourceManager.GetString("TA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Третье число рассчитывали через умножение и вычитание, а вычитание - уменьшение (уход назад по времени). 
        ''' Предположим, что число третье и четвертое, полученное из третьего, отвечают за те качества, которые были даны человеку от рождения. Можно сказать, что эти цифры во многом определили родители.
        '''</summary>
        Friend Shared ReadOnly Property TRC() As String
            Get
                Return ResourceManager.GetString("TRC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Интересен тот факт, что Пифагор использовал идею о многих воплощениях души человека в различных телах после смерти. Выполнив расчет, он использовал его для вычисления «номера жизни» человека, сосчитав количество цифр в полученном расчете (без цифры 0). 
        '''Если вам это нравится - пользуйтесь, но помните, что больше 15 цифр не будет. Пифагор считал, что душа имеет только 15 воплощений в других телах.
        '''</summary>
        Friend Shared ReadOnly Property VO() As String
            Get
                Return ResourceManager.GetString("VO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Второе число показывает ведущее качество человека и основную цель его появления на Земле.
        '''</summary>
        Friend Shared ReadOnly Property VRC() As String
            Get
                Return ResourceManager.GetString("VRC", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
